language: node_js
node_js: node
cache: npm
os:
  - linux
  - osx
script:
  - npm test
  - '[ "$TRAVIS_OS_NAME" != linux ] || npm run --silent verify-definitions -- $TRAVIS_COMMIT_RANGE'
notifications:
  email:
    on_success: never
