name: Lint LTS Warnings
on:
  pull_request:
  push: { branches: master }
  schedule: [{ cron:  '0 0 * * *' }] # daily: https://crontab.guru/#0_0_*_*_*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run lint:lts -- --fix
