name: Lint Checksums
on:
  pull_request: { paths: 'share/node-build/**' }

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch base_ref HEAD
      run: git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
    - run: npm ci
    - run: npm run lint:checksums -- origin/${{github.base_ref}}
