name: Generate Definitions
on:
  schedule: [{ cron:  '0 */4 * * *' }] # every 4 hrs: https://crontab.guru/#0_*/4_*_*_*
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: npm run scrape-definitions
    - run: npm run lint:lts -- --fix
      continue-on-error: true
    - run: npm run commit-definitions
      env:
        GIT_AUTHOR_NAME: 'nodenv bot'
        GIT_AUTHOR_EMAIL: 'nodenv-bot@users.noreply.github.com'
        GIT_COMMITTER_NAME: 'nodenv bot'
        GIT_COMMITTER_EMAIL: 'nodenv-bot@users.noreply.github.com'
    - id: log
      run: |
        msg=$(git log --format='- %s' --reverse ${{github.sha}}..)
        echo "message=${msg//$'\n'/'%0A'}" >> $GITHUB_OUTPUT
    - uses: peter-evans/create-pull-request@v5
      with:
        branch: latest-scraped-definitions
        title: 'Scraped latest definitions'
        body: ${{ steps.log.outputs.message }}
