name: Generate Definitions
on:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hrs

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci --prefer-offline --no-audit
    - run: npm run scrape-definitions
